version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - ./data/minio:/data

    restart: unless-stopped

  spark:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: spark

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

    ports:
      - "8080:8080"
      - "7077:7077"

    volumes:
      - ./spark:/opt/spark-apps
      - ./data:/data

    depends_on:
      - postgres
      - minio

    restart: unless-stopped

  trino:
    image: trinodb/trino:454

    container_name: trino

    ports:
      - "8081:8080"

    volumes:
      - ./docker/trino/catalog:/etc/trino/catalog

    depends_on:
      - postgres
      - minio

  superset:
    image: apache/superset:latest

    container_name: superset

    ports:
      - "8088:8088"

    environment:
      SUPERSET_SECRET_KEY: lakehouse-secret

    depends_on:
      - trino

  airflow-postgres:
    image: postgres:16

    container_name: airflow-postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    ports:
      - "5433:5432"

    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.10.0

    container_name: airflow-init

    depends_on:
      airflow-postgres:
        condition: service_healthy

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
        --username admin
        --password admin
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@example.com
      "

    restart: "no"

  airflow-webserver:
    image: apache/airflow:2.10.0

    container_name: airflow-webserver

    depends_on:
      - airflow-postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key_123

    ports:
      - "8089:8080"

    command: webserver

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark:/opt/spark-apps
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.10.0

    container_name: airflow-scheduler

    depends_on:
      - airflow-postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key_123

    command: scheduler

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark:/opt/spark-apps
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped

volumes:
  airflow_postgres_data:
